routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});


Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('generos', App\Http\Controllers\GeneroController::class);

Route::resource('municipios', App\Http\Controllers\MunicipioController::class);

Route::resource('localidades', App\Http\Controllers\LocalidadesController::class);

Route::get('localidades/get-localidades/{id_mun}', 'OficinasController@getLocalidades');

Route::resource('dependencias', App\Http\Controllers\DependenciasController::class);

Route::resource('oficinas', App\Http\Controllers\OficinasController::class);

Route::resource('tipoClientes', App\Http\Controllers\Tipo_ClientesController::class);

Route::resource('clientes', App\Http\Controllers\ClientesController::class);

Route::resource('bitacoras', App\Http\Controllers\BitacoraController::class);

Route::get('bitacoras/index/{id_cliente}',[App\Http\Controllers\BitacoraController::class, 'index']
)->name('bitacoras.index')->middleware('verified');

Route::get('bitacoras/index/{id_cliente}/create',[App\Http\Controllers\BitacoraController::class, 'create']
)->name('bitacoras.create')->middleware('verified');

/*Route::get('bitacoras/edit/{id_cliente}',[App\Http\Controllers\BitacoraController::class, 'edit']
)->name('bitacoras.edit')->middleware('verified');*/

Route::resource('prospectos', App\Http\Controllers\ProspectoController::class);

Route::resource('bitacoraProspectos', App\Http\Controllers\Bitacora_ProspectoController::class);

Route::get('bitacoraProspectos/index/{id_prospecto}',[App\Http\Controllers\Bitacora_ProspectoController::class, 'index']
)->name('bitacoraProspectos.index')->middleware('verified');

Route::get('bitacoraProspectos/index/{id_prospecto}/create',[App\Http\Controllers\Bitacora_ProspectoController::class, 'create']
)->name('bitacoraProspectos.create')->middleware('verified');

//rutas para los reportes
Route::resource('reportes', App\Http\Controllers\ReporteController::class);

Route::get('reportes/municipio/', [App\Http\Controllers\ReporteController::class, 'show'])
         ->name('reportes.municipio')->middleware('verified');

Route::post('reportes/municipio/municipioPDF', [App\Http\Controllers\ReporteController::class, 'municipioPDF'])
         ->name('reportes.municipioPDF')->middleware('verified');


Route::resource('reportesDependencias', App\Http\Controllers\ReporteDependenciasController::class);

Route::get('reportesDependencias/dependencias/', [App\Http\Controllers\ReporteDependenciasController::class, 'show'])
         ->name('reportesDependencias.dependencias')->middleware('verified');

Route::post('reportesDependencias/dependencias/dependenciaPDF', [App\Http\Controllers\ReporteDependenciasController::class, 'dependenciaPDF'])
         ->name('reportesDependencias.dependenciaPDF')->middleware('verified');

app/Models/Bitacora_Prospecto.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class Bitacora_Prospecto
 * @package App\Models
 * @version May 8, 2021, 2:59 pm EST
 *
 * @property integer $id_prospecto
 * @property string $fecha
 * @property string $observaciones
 */
class Bitacora_Prospecto extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'bitacora_prospecto';
    

    protected $dates = ['deleted_at'];


    protected $primaryKey = 'id_bitacora_prospecto';

    public $fillable = [
        'id_prospecto',
        'fecha',
        'observaciones'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id_bitacora_prospecto' => 'integer',
        'id_prospecto' => 'integer',
        'fecha' => 'date',
        'observaciones' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/Bitacora_ProspectoController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\Bitacora_ProspectoDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateBitacora_ProspectoRequest;
use App\Http\Requests\UpdateBitacora_ProspectoRequest;
use App\Repositories\Bitacora_ProspectoRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class Bitacora_ProspectoController extends AppBaseController
{
    /** @var  Bitacora_ProspectoRepository */
    private $bitacoraProspectoRepository;

    public function __construct(Bitacora_ProspectoRepository $bitacoraProspectoRepo)
    {
        $this->bitacoraProspectoRepository = $bitacoraProspectoRepo;
    }

    /**
     * Display a listing of the Bitacora_Prospecto.
     *
     * @param Bitacora_ProspectoDataTable $bitacoraProspectoDataTable
     * @return Response
     */
    public function index($id_prospecto, Bitacora_ProspectoDataTable $bitacoraProspectoDataTable)
    {
        $id_prospecto = decrypt($id_prospecto);
        

        $prospecto=\DB::table('prospecto')
            ->select('prospecto.*', 'dependencias.nombre_dependencia as dependencia', 'oficinas.nombre_oficina as oficina', 'tipo_clientes.nombre_tipo as tipo_cliente')
            ->join('dependencias','dependencias.id_dependencia','=','prospecto.id_dependencia')
            ->join('oficinas','oficinas.id_oficina','=','prospecto.id_oficina')
            ->join('tipo_clientes','tipo_clientes.id_tipo_cliente','=','prospecto.id_tipo_cliente')
            ->where("id_prospecto", "=", $id_prospecto)
            ->get()
            ->all();

        //dd($prospecto);

        return $bitacoraProspectoDataTable->with('id_prospecto', $id_prospecto)->render('bitacora__prospectos.index',['prospecto'=>$prospecto]);
    }

    /**
     * Show the form for creating a new Bitacora_Prospecto.
     *
     * @return Response
     */
    public function create($id_prospecto)
    {
        $id_prospecto = decrypt($id_prospecto);

        //dd($id_prospecto);

        $prospecto=\DB::table('prospecto')
            ->select('prospecto.*', 'dependencias.nombre_dependencia as dependencia', 'oficinas.nombre_oficina as oficina', 'tipo_clientes.nombre_tipo as tipo_cliente')
            ->join('dependencias','dependencias.id_dependencia','=','prospecto.id_dependencia')
            ->join('oficinas','oficinas.id_oficina','=','prospecto.id_oficina')
            ->join('tipo_clientes','tipo_clientes.id_tipo_cliente','=','prospecto.id_tipo_cliente')
            ->where("id_prospecto", "=", $id_prospecto)
            ->get()
            ->all();

        //dd($prospecto);
        
        return view('bitacora__prospectos.create')->with('prospecto', $prospecto);
    }

    /**
     * Store a newly created Bitacora_Prospecto in storage.
     *
     * @param CreateBitacora_ProspectoRequest $request
     *
     * @return Response
     */
    public function store(CreateBitacora_ProspectoRequest $request)
    {
        $input = $request->all();

        $id_prospecto=$input['id_prospecto'];

        $bitacoraProspecto = $this->bitacoraProspectoRepository->create($input);

        Flash::success(__('messages.saved', ['model' => __('models/bitacoraProspectos.singular')]));

        return redirect(route('bitacoraProspectos.index',encrypt($id_prospecto)));
    }

    /**
     * Display the specified Bitacora_Prospecto.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $bitacoraProspecto = $this->bitacoraProspectoRepository->find($id);

        if (empty($bitacoraProspecto)) {
            Flash::error(__('messages.not_found', ['model' => __('models/bitacoraProspectos.singular')]));

            return redirect(route('bitacoraProspectos.index'));
        }

        return view('bitacora__prospectos.show')->with('bitacoraProspecto', $bitacoraProspecto);
    }

    /**
     * Show the form for editing the specified Bitacora_Prospecto.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {

        $bitacoraProspecto = $this->bitacoraProspectoRepository->find($id);

        $id_prospecto=$bitacoraProspecto->id_prospecto;

        $prospecto=\DB::table('prospecto')
            ->select('prospecto.*', 'dependencias.nombre_dependencia as dependencia', 'oficinas.nombre_oficina as oficina', 'tipo_clientes.nombre_tipo as tipo_cliente')
            ->join('dependencias','dependencias.id_dependencia','=','prospecto.id_dependencia')
            ->join('oficinas','oficinas.id_oficina','=','prospecto.id_oficina')
            ->join('tipo_clientes','tipo_clientes.id_tipo_cliente','=','prospecto.id_tipo_cliente')
            ->where("id_prospecto", "=", $id_prospecto)
            ->get()
            ->all();

        //dd($bitacoraProspecto);

        if (empty($bitacoraProspecto)) {
            Flash::error(__('messages.not_found', ['model' => __('models/bitacoraProspectos.singular')]));

            return redirect(route('bitacoraProspectos.index'));
        }

        return view('bitacora__prospectos.edit')->with('bitacoraProspecto', $bitacoraProspecto)->with('prospecto', $prospecto);
    }

    /**
     * Update the specified Bitacora_Prospecto in storage.
     *
     * @param  int              $id
     * @param UpdateBitacora_ProspectoRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateBitacora_ProspectoRequest $request)
    {
        $bitacoraProspecto = $this->bitacoraProspectoRepository->find($id);

        $input = $request->all();
        $id_prospecto=$input['id_prospecto'];

        if (empty($bitacoraProspecto)) {
            Flash::error(__('messages.not_found', ['model' => __('models/bitacoraProspectos.singular')]));

            return redirect(route('bitacoraProspectos.index'));
        }

        $bitacoraProspecto = $this->bitacoraProspectoRepository->update($request->all(), $id);

        Flash::success(__('messages.updated', ['model' => __('models/bitacoraProspectos.singular')]));

        return redirect(route('bitacoraProspectos.index',encrypt($id_prospecto)));
    }

    /**
     * Remove the specified Bitacora_Prospecto from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $bitacoraProspecto = $this->bitacoraProspectoRepository->find($id);

        //dd($bitacoraProspecto);

        $id_prospecto=$bitacoraProspecto->id_prospecto;

        if (empty($bitacoraProspecto)) {
            Flash::error(__('messages.not_found', ['model' => __('models/bitacoraProspectos.singular')]));

            return redirect(route('bitacoraProspectos.index'));
        }

        $this->bitacoraProspectoRepository->delete($id);

        Flash::success(__('messages.deleted', ['model' => __('models/bitacoraProspectos.singular')]));

        return redirect(route('bitacoraProspectos.index',encrypt($id_prospecto)));
    }
}

resources/views/bitacora__prospectos/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            @lang('models/bitacoraProspectos.singular')
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <fieldset>
                        <legend>Datos del solicitante:</legend>

                        @foreach ($prospecto as $pros)
                            <!-- Nombre Cliente Field -->
                            <div class="form-group col-sm-6">
                            {!! Form::label('nombre_prospecto','Nombre cliente prospecto:') !!}
                            <p>{{ $pros->nombre_prospecto }}</p>
                        </div>

                        <!-- Rfc Cliente Field -->
                        <div class="form-group col-sm-6">
                            {!! Form::label('rfc_prospecto', 'RFC cliente prospecto:') !!}
                            <p>{{ $pros->rfc_prospecto }}</p>
                        </div>

                        <!-- Telefono Field -->
                        <div class="form-group col-sm-6">
                            {!! Form::label('telefono', __('models/clientes.fields.telefono').':') !!}
                            <p>{{ $pros->telefono }}</p>
                        </div>

                        <!-- Id Dependencia Field -->
                        <div class="form-group col-sm-6">
                            {!! Form::label('id_dependencia', __('models/clientes.fields.id_dependencia').':') !!}
                            <p>{{ $pros->dependencia }}</p>
                        </div>

                        <!-- Id Oficina Field -->
                        <div class="form-group col-sm-6">
                            {!! Form::label('id_oficina', __('models/clientes.fields.id_oficina').':') !!}
                            <p>{{ $pros->oficina }}</p>
                        </div>

                        <!-- Correo Electronico Field -->
                        <div class="form-group col-sm-6">
                            {!! Form::label('correo_electronico', __('models/clientes.fields.correo_electronico').':') !!}
                            <p>{{ $pros->correo_electronico }}</p>
                        </div>

                        <!-- Id Tipo Cliente Field -->
                        <div class="form-group col-sm-6">
                            {!! Form::label('id_tipo_cliente', __('models/clientes.fields.id_tipo_cliente').':') !!}
                            <p>{{ $pros->tipo_cliente }}</p>
                        </div>

                        <!-- Id Tipo Cliente Field -->
                        <div class="form-group col-sm-6">
                            {!! Form::label('created_at', 'Creado el:') !!}
                            <p>{{ $pros->created_at }}</p>
                        </div>

                        @endforeach
                    </fieldset>
                    
                <div class="row">
                    {!! Form::open(['route' => 'bitacoraProspectos.store']) !!}

                        @include('bitacora__prospectos.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/bitacora__prospectos/datatables_actions.blade.php
{!! Form::open(['route' => ['bitacoraProspectos.destroy', $id_bitacora_prospecto], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('bitacoraProspectos.edit', $id_bitacora_prospecto) }}" class='btn btn-warning btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => 'return confirm("'.__('crud.are_you_sure').'")'
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/bitacora__prospectos/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            @lang('models/bitacoraProspectos.singular')
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($bitacoraProspecto, ['route' => ['bitacoraProspectos.update', $bitacoraProspecto->id_bitacora_prospecto], 'method' => 'patch']) !!}

                        @include('bitacora__prospectos.fieldsedit')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/bitacora__prospectos/fields.blade.php
@foreach ($prospecto as $pros)

    <!-- Id Prospecto Field -->
        {!! Form::hidden('id_prospecto', $pros->id_prospecto, ['class' => 'form-control']) !!}


    <!-- Fecha Field -->
    <div class="form-group col-sm-6">
        {!! Form::label('fecha', __('models/bitacoraProspectos.fields.fecha').':') !!}
        {!! Form::date('fecha', null, ['class' => 'form-control','id'=>'fecha']) !!}
    </div>

    <!-- Observaciones Field -->
    <div class="form-group col-sm-12 col-lg-12">
        {!! Form::label('observaciones', __('models/bitacoraProspectos.fields.observaciones').':') !!}
        {!! Form::textarea('observaciones', null, ['class' => 'form-control']) !!}
    </div>

    <!-- Submit Field -->
    <div class="form-group col-sm-12">
        {!! Form::submit(__('crud.save'), ['class' => 'btn btn-primary']) !!}
        <a href="{{ route('bitacoraProspectos.index', Crypt::encrypt($pros->id_prospecto)) }}" class="btn btn-default">@lang('crud.cancel')</a>
    </div>

@endforeach

resources/views/bitacora__prospectos/fieldsedit.blade.php
@foreach ($prospecto as $pros)

    <!-- Id Prospecto Field -->
        {!! Form::hidden('id_prospecto', $pros->id_prospecto, ['class' => 'form-control']) !!}


    <!-- Fecha Field -->
    <div class="form-group col-sm-6">
        {!! Form::label('fecha', __('models/bitacoraProspectos.fields.fecha').':') !!}
        {!! Form::date('fecha', null, ['class' => 'form-control','id'=>'fecha']) !!}
    </div>

    <!-- Observaciones Field -->
    <div class="form-group col-sm-12 col-lg-12">
        {!! Form::label('observaciones', __('models/bitacoraProspectos.fields.observaciones').':') !!}
        {!! Form::textarea('observaciones', null, ['class' => 'form-control']) !!}
    </div>

    <!-- Submit Field -->
    <div class="form-group col-sm-12">
        {!! Form::submit(__('crud.save'), ['class' => 'btn btn-primary']) !!}
        <a href="{{ route('bitacoraProspectos.index', Crypt::encrypt($pros->id_prospecto)) }}" class="btn btn-default">@lang('crud.cancel')</a>
    </div>

@endforeach

resources/views/bitacora__prospectos/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">
            @lang('models/bitacoraProspectos.singular')
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                <div>
                    @foreach ($prospecto as $pros)
                        <!-- Nombre Cliente Field -->
                        <div class="form-group col-sm-6">
                            {!! Form::label('nombre_prospecto','Nombre cliente prospecto:') !!}
                            <p>{{ $pros->nombre_prospecto }}</p>
                        </div>

                        <!-- Rfc Cliente Field -->
                        <div class="form-group col-sm-6">
                            {!! Form::label('rfc_prospecto', 'RFC cliente prospecto:') !!}
                            <p>{{ $pros->rfc_prospecto }}</p>
                        </div>

                        <!-- Telefono Field -->
                        <div class="form-group col-sm-6">
                            {!! Form::label('telefono', __('models/clientes.fields.telefono').':') !!}
                            <p>{{ $pros->telefono }}</p>
                        </div>

                        <!-- Id Dependencia Field -->
                        <div class="form-group col-sm-6">
                            {!! Form::label('id_dependencia', __('models/clientes.fields.id_dependencia').':') !!}
                            <p>{{ $pros->dependencia }}</p>
                        </div>

                        <!-- Id Oficina Field -->
                        <div class="form-group col-sm-6">
                            {!! Form::label('id_oficina', __('models/clientes.fields.id_oficina').':') !!}
                            <p>{{ $pros->oficina }}</p>
                        </div>

                        <!-- Correo Electronico Field -->
                        <div class="form-group col-sm-6">
                            {!! Form::label('correo_electronico', __('models/clientes.fields.correo_electronico').':') !!}
                            <p>{{ $pros->correo_electronico }}</p>
                        </div>

                        <!-- Id Tipo Cliente Field -->
                        <div class="form-group col-sm-6">
                            {!! Form::label('id_tipo_cliente', __('models/clientes.fields.id_tipo_cliente').':') !!}
                            <p>{{ $pros->tipo_cliente }}</p>
                        </div>

                        <!-- Id Tipo Cliente Field -->
                        <div class="form-group col-sm-6">
                            {!! Form::label('created_at', 'Creado el:') !!}
                            <p>{{ $pros->created_at }}</p>
                        </div>

                        <a class="btn btn-default btn-sm no-corner" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('bitacoraProspectos.create', Crypt::encrypt($pros->id_prospecto)) !!}"><i class="glyphicon glyphicon-plus"></i>Agregar Observación</a>
                    @endforeach

                </div>
                    @include('bitacora__prospectos.table')

                    <a href="{!! route('prospectos.index') !!}" class="btn btn-primary">Regresar</a>
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/bitacora__prospectos/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            @lang('models/bitacoraProspectos.singular')
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('bitacora__prospectos.show_fields')
                    <a href="{{ route('bitacoraProspectos.index') }}" class="btn btn-default">
                        @lang('crud.back')
                    </a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/bitacora__prospectos/show_fields.blade.php
<!-- Id Prospecto Field -->
<div class="form-group">
    {!! Form::label('id_prospecto', __('models/bitacoraProspectos.fields.id_prospecto').':') !!}
    <p>{{ $bitacoraProspecto->id_prospecto }}</p>
</div>

<!-- Fecha Field -->
<div class="form-group">
    {!! Form::label('fecha', __('models/bitacoraProspectos.fields.fecha').':') !!}
    <p>{{ $bitacoraProspecto->fecha }}</p>
</div>

<!-- Observaciones Field -->
<div class="form-group">
    {!! Form::label('observaciones', __('models/bitacoraProspectos.fields.observaciones').':') !!}
    <p>{{ $bitacoraProspecto->observaciones }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', __('models/bitacoraProspectos.fields.created_at').':') !!}
    <p>{{ $bitacoraProspecto->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', __('models/bitacoraProspectos.fields.updated_at').':') !!}
    <p>{{ $bitacoraProspecto->updated_at }}</p>
</div>

resources/views/bitacora__prospectos/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@push('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush